[package]
name = "rusty_reversi"
version = "0.0.1"
authors = [ "David Szakallas <david.szakallas@gmail.com>" ]
license = "MIT"

[lib]
name = "rusty_reversi"
crate-type = ["dylib", "rlib"]

[dependencies]
